services:
  - type: web
    name: aeronav-server
    env: node
    region: oregon
    plan: free
    repo: https://github.com/romeo8580/AeroNav_Deploy
    rootDir: .
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: REVENUECAT_API_KEY
        sync: false
      - key: REVENUECAT_WEBHOOK_SECRET
        sync: false

