services:
  - type: web
    name: aeronav-server
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: REVENUECAT_API_KEY
        sync: false
      - key: REVENUECAT_WEBHOOK_SECRET
        sync: false