services:
  - type: web
    name: aeronav
    env: node
    rootDir: server
    buildCommand: |
      cd ../frontend
      npm install
      npm run build
      cd ../server
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
