services:
  - type: web
    name: aeronav-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  - type: static
    name: aeronav-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_BASE_URL
        sync: false
